# Generated by Django 3.2.21 on 2023-10-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20231014_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cash')),
                ('checks', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Checks')),
                ('creditcard', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Credit Card')),
                ('creditcard_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Credit Card Fee')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total')),
            ],
        ),
        migrations.AlterField(
            model_name='accountspayable',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
    ]
