# Generated by Django 3.2.21 on 2023-09-13 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20230906_1651'),
        ('krueger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kruegerjobdetail',
            name='customer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='kruegerjobdetail',
            name='jobquote',
            field=models.CharField(choices=[('Workorder', 'Workorder'), ('Quote', 'Quote')], max_length=100, verbose_name='Workorder or Quote'),
        ),
        migrations.AlterField(
            model_name='kruegerjobdetail',
            name='set_per_book',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='# of sets / books/ pieces'),
        ),
    ]
