# Generated by Django 3.2.21 on 2023-09-22 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krueger', '0002_auto_20230913_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.CharField(blank=True, max_length=100, null=True, verbose_name='Paper')),
                ('price_per_m', models.CharField(blank=True, max_length=100, null=True, verbose_name='Paper Stock Price per M')),
            ],
        ),
        migrations.AlterField(
            model_name='kruegerjobdetail',
            name='paper_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='krueger.paperstock'),
        ),
    ]
