# Generated by Django 3.2.21 on 2023-09-22 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('krueger', '0004_auto_20230922_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperstock',
            name='manufacturer',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100, verbose_name='manufacturer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paperstock',
            name='size',
            field=models.CharField(blank=True, max_length=100, verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='paperstock',
            name='weight',
            field=models.CharField(blank=True, max_length=100, verbose_name='weight'),
        ),
    ]
