# Generated by Django 3.2.21 on 2023-09-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krueger', '0005_auto_20230922_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperstock',
            name='manufacturer',
            field=models.CharField(max_length=100, verbose_name='manufacturer'),
        ),
        migrations.AlterField(
            model_name='paperstock',
            name='size',
            field=models.CharField(max_length=100, verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='paperstock',
            name='weight',
            field=models.CharField(max_length=100, verbose_name='weight'),
        ),
    ]
