# Generated by Django 3.2.21 on 2023-10-11 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('krueger', '0006_auto_20230922_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperstock',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paperstock',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='manufacturer'),
        ),
    ]
