# Generated by Django 3.2.21 on 2023-10-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krueger', '0008_misccost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misccost',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='price each'),
        ),
    ]
