# Generated by Django 3.2.21 on 2023-10-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krueger', '0009_alter_misccost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='step_drill_price',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Drill'),
        ),
    ]
