# Generated by Django 3.2.21 on 2023-10-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krueger', '0010_kruegerjobdetail_step_drill_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='misc1_description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Misc extra 1 description'),
        ),
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='misc1_price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Misc extra 1 price'),
        ),
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='misc2_description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Misc extra 2 description'),
        ),
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='misc2_price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Misc extra 2 price'),
        ),
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='misc3_description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Misc extra 3 description'),
        ),
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='misc3_price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Misc extra 3 price'),
        ),
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='misc4_description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Misc extra 4 description'),
        ),
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='misc4_price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Misc extra 4 price'),
        ),
    ]
