# Generated by Django 3.2.21 on 2023-09-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('address1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adddress 2')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(max_length=100, null=True, verbose_name='State')),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zipcode')),
                ('phone1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone 1')),
                ('phone2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone 2')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, max_length=100, null=True, verbose_name='Website')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
